### ISSUE TITLE
Organization members include service account records

### ISSUE THREAD

**Issue by splatch** [p2-inc/keycloak-orgs#40] opened 2023-02-17 23:17 UTC
Detected with 19.0.2 version with PostgreSQL. I am not aware of specific logic in membership associations, but I found that calling phase two client returns extra membership entries which do not belong to organization: 

```java
List<UserRepresentation> members = client.getOrganizationMembershipsApi().getOrganizationMemberships(
  realm, orgId, 0, 200
);
```

I first thought that it was mistake in calculated URI, but after enabling logging I found that it is fine:
```
jaxrs.LoggingInterceptor (LoggingInterceptor.java:22) - Request 97654a55-0645-4e7f-88d4-2e4d7891d146, GET http://keycloak:8080/auth/realms/test/orgs/3c2cb198-a597-4238-b31a-db3bccb4c421/members?first=0&max=200
```

The above code gives me a user record which represents service account of an client. I traced it down to server code which, for some reason, includes service account. By looking at database entities I haven't found a clear reason why it would happen.
Note that there was issue #32 which noted use of admin-cli which uses service accounts, but it was closed as resolved. I think it could be subject of similar issue where removal of organization could lead to removal of service account which results in re-creation of user record representing service account by Keycloak itself. Difference is, newly created user will loose all roles it had assigned before.

**Comment by xgp** [comment] 2023-02-19 10:55
Yes, the method to get organization members currently returns organization service accounts. Is this an issue for you?

> I think it could be subject of similar issue where removal of organization could lead to removal of service account which results in re-creation of user record representing service account by Keycloak itself. Difference is, newly created user will loose all roles it had assigned before.

This point doesn't make sense to me. How would this happen?

**Comment by splatch** [comment] 2023-02-19 12:16
For me it returns service account which is created during realm import, before any organization could even be created. Client itself is also created during realm import and have nothing to do with any of organizations registered in system.

**Comment by xgp** [comment] 2023-02-20 09:53
I see. This extension doesn't support realm import/export. We haven't figured out how to hook into the Keycloak import/export process, so the tree of organization information is lost in a realm export. However, because the organization service account is a real user, that gets exported.

**Comment by splatch** [comment] 2023-02-20 21:24
I kind of understand implications on import/export. Reason why I was completely surprised is fact that membership resource returns extra entries, beyond ones which are expected to come from database entries (organizations membership). There is no relation between service account and organization, how it is possible that it is considered to be a member of an org?

**Comment by xgp** [comment] 2023-02-21 19:00
It is returning members for which there is no `ORGANIZATION_MEMBER` record in the DB? If so, can you post your full request and a `select *` from your `ORGANIZATION` AND `ORGANIZATION_MEMBER` tables?

**Comment by xgp** [comment] 2023-03-02 22:45
Closing pending detail to recreate the bug. Please reopen with comprehensive information about how to reproduce.

**Closed by xgp** 2023-03-02 22:45 UTC
